#############################################################################
# Makefile for building: qt-skeleton
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Mar 28 02:17:15 2012
# Project:  qt-skeleton.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qt-skeleton.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MyPaint.cpp \
		Puny.cpp \
		Enemy.cpp \
		Board.cpp moc_MyPaint.cpp \
		qrc_towerdefense.cpp
OBJECTS       = main.o \
		MyPaint.o \
		Puny.o \
		Enemy.o \
		Board.o \
		moc_MyPaint.o \
		qrc_towerdefense.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qt-skeleton.pro
QMAKE_TARGET  = qt-skeleton
DESTDIR       = 
TARGET        = qt-skeleton

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt-skeleton.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile qt-skeleton.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qt-skeleton.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qt-skeleton1.0.0 || $(MKDIR) .tmp/qt-skeleton1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt-skeleton1.0.0/ && $(COPY_FILE) --parents MyPaint.h Puny.h Enemy.h Board.h .tmp/qt-skeleton1.0.0/ && $(COPY_FILE) --parents towerdefense.qrc .tmp/qt-skeleton1.0.0/ && $(COPY_FILE) --parents main.cpp MyPaint.cpp Puny.cpp Enemy.cpp Board.cpp .tmp/qt-skeleton1.0.0/ && (cd `dirname .tmp/qt-skeleton1.0.0` && $(TAR) qt-skeleton1.0.0.tar qt-skeleton1.0.0 && $(COMPRESS) qt-skeleton1.0.0.tar) && $(MOVE) `dirname .tmp/qt-skeleton1.0.0`/qt-skeleton1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt-skeleton1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MyPaint.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MyPaint.cpp
moc_MyPaint.cpp: Board.h \
		Tower.h \
		Enemy.h \
		MyPaint.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MyPaint.h -o moc_MyPaint.cpp

compiler_rcc_make_all: qrc_towerdefense.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_towerdefense.cpp
qrc_towerdefense.cpp: towerdefense.qrc \
		map1.txt
	/usr/bin/rcc -name towerdefense towerdefense.qrc -o qrc_towerdefense.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp MyPaint.h \
		Board.h \
		Tower.h \
		Enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MyPaint.o: MyPaint.cpp Board.h \
		Tower.h \
		Enemy.h \
		MyPaint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyPaint.o MyPaint.cpp

Puny.o: Puny.cpp Enemy.h \
		Puny.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Puny.o Puny.cpp

Enemy.o: Enemy.cpp Enemy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Enemy.o Enemy.cpp

Board.o: Board.cpp Board.h \
		Tower.h \
		Enemy.h \
		Puny.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Board.o Board.cpp

moc_MyPaint.o: moc_MyPaint.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyPaint.o moc_MyPaint.cpp

qrc_towerdefense.o: qrc_towerdefense.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_towerdefense.o qrc_towerdefense.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

